### ISSUE TITLE
Prefer secure conection over normal.

### ISSUE THREAD

**Issue by drielnox** [icechat/IceChat#10]

**Comment by icechat** [comment]
Sadly, a lot of IRC networks do not have SSL, so this would be mundane.
Port 6667 is the default IRC port, and it also is not SSL.

**Comment by drielnox** [comment]
Mundane? Does that mean that, for the simple fact that there are few IRC networks without secure connection, there is no intention to implement it?
I think no matter if there are few or many networks with or without security. I think it must be independent of any condition.
Moreover, it would be a nice feature for the application.

**Comment by icechat** [comment]
There is no point in implenenting it, the user can select SSL/Port themselves. 
If SSL is default, you cant even connect to quakenet, the default #icechat help channel.
Its not a bad suggestion, but I think it would cause more problems,
