### ISSUE TITLE
Settings -> Main -> Time stamp have a "localized default" option

### ISSUE THREAD

**Issue by gbakeman** [icechat/IceChat#13]
The current default for the time stamp appears to be an hour:minute:second representation, although the .Net framework provides a [standard time representation "T"](https://msdn.microsoft.com/en-us/library/az4se3k1%28v=vs.110%29.aspx#LongTime) that automatically formats based on the user's current culture. Perhaps it may be useful if the Time stamp option has a button that defaults it to that T value?

**Comment by icechat** [comment]
The time stamp can be changed to whatever you want, in settings,so there is no need for a setting like this. The default is just [HH:mm.ss]
