### ISSUE TITLE
can't scroll through text window

### ISSUE THREAD

**Issue by blueberryapple** [icechat/IceChat#14]
With icechat 9.10, can't scroll up or down in the chat window unless cursor is on top of scroll bar.

**Comment by icechat** [comment]
I am guessing you are using Windows 10, and this is a Windows 10 issue.
There is a setting to fix this in the Mouse Settings, called "scroll inactive windows when I hover over them" 
Changing the setting fixes the problem.

**Comment by blueberryapple** [comment]
Turning that setting off fixed the problem. Thanks.

**Comment by gbakeman** [comment]
If I may add to this, there appears to be a relatively simple way to fix this in-app. (See this answer: https://stackoverflow.com/a/4766428).

**Comment by icechat** [comment]
That is not the issue, the issue is with Windows 10 settings.

http://www.icechat.net/forums/index.php?topic=1842.0
