### ISSUE TITLE
highlite plugin improvement

### ISSUE THREAD

**Issue by ExileFox** [icechat/IceChat#15]
[ ] Highlight only whole word matches
[ ] Highlight only exact matches

<Example> {highlight start}user1234{highlight end} string123 something
<Example> {highlight start}user{highlight end}1234 string123 something

The first one would be a major improvement

**Comment by icechat** [comment]
The highlighter can use REGEX to do matches, so this is already implemented.

**Comment by ExileFox** [comment]
I see. Only problem is to generate that. RegEx has always been a pain to
work with.

**Comment by icechat** [comment]
It seems the Regex isn't really perfect either, as to how it is currently being used, so I will probably have a checkbox to match with Regex.
As for how to use it, a Wiki page can be made to help with some basics.

**Comment by icechat** [comment]
To use whole word matches, wrap the word in \b .. Example.
\buser1234\b
An exact match would be a word match as per above. This works in the current version of the highlighter.

**Comment by ExileFox** [comment]
Aha, okay.
