### ISSUE TITLE
Dividers and scroll bars lack color settings

### ISSUE THREAD

**Issue by mikeloeven** [icechat/IceChat#19]
Just a minor issue when trying to go for a fully dark theme I noticed that scroll bars as well as dividing bars had no accessible color setting which causes a bit of a disjointed appearance where the light grey lines conflict with darker settings

**Comment by icechat** [comment]
Yes, there is currently no way to change the colors of Scroll Bars.
Thanks

**Comment by icechat** [comment]
The Splitters now have a Color Setting under Other, Side Panel Splitter.

**Comment by alienfxfiend** [comment]
Not a problem if you have [Stardock] WindowBlinds 10, it skins everything, there are some dark skins like: https://www.wincustomize.com/explore/windowblinds/8994/ (Blue Dream) You need the app though. Alternatively, you can use this High-Contrast theme (works as a Windows 10 theme so you don't have to toggle it, very fast, however you will lose the lock screen bg image (you can re-apply the wallpaper again) & Office & other background will be black, which is the tradeoff. —you don't need third-party UxTheme patcher or anything, works OOB) ~> https://www.deviantart.com/eversins/art/GreyEveTheme-FINAL-Windows-10-High-Contrast-Theme-643504863
