### ISSUE TITLE
IceChat beta updates?

### ISSUE THREAD

**Issue by gbakeman** [icechat/IceChat#21]
I see you're possibly gearing up for a 9.19 release, and I'd love to help test pre-release versions if that might provide valuable feedback. I see that IceChat use to do beta releases; could this system be brought back, and preferably in such a way that the updater could optionally automatically update us to beta versions?

**Comment by icechat** [comment]
I don't release Beta versions any more, too tedious.
If you want to use the latest "Source" releases, download the code, and use the Build batch files that are in the Build folder, to build your own. It is very easy to do.

**Comment by gbakeman** [comment]
Anything I can do to help!

**Comment by icechat** [comment]
#icechat on Freenode is also our development channel, always good to get info there.
