### ISSUE TITLE
IceChat 9.21 consumes almost 100% of CPU on Windows 10 Pro

### ISSUE THREAD

**Issue by Naktibalda** [icechat/IceChat#24]
Usually it happens right after launching IceChat.
It doesn't happen everytime, but when it does, IceChat is unusably slow for a long period of time and I have to turn it off.

![image](https://user-images.githubusercontent.com/395992/53336614-7a3ec880-3907-11e9-8690-0470d0b4c16e.png)

**Comment by Naktibalda** [comment]
I didn't turn it off this time and CPU usage went down to 0% in 15-20 minutes.

**Comment by Naktibalda** [comment]
Icechat behaved well for 29 days, now it is consuming 99.5% of 1 core for 33 minutes and it hasn't even completed joining channels yet on the second network out of two networks I use.
It shows that it joined the channel at 13:07, but it doesn't display topic, users or messages yet.

It could be caused by some kind of monthly task.

**Comment by Naktibalda** [comment]
Disconnecting from both networks made no difference,
After reconnecting to second network CPU usage went down.
This issue lasted 46 minutes.

When I disconnected from second network, I got this error:
```
[13:53.37] ERROR: OnReceivedData Exception Error:Unable to read data from the transport connection: The IAsyncResult object was not returned from the corresponding asynchronous method on this class.
[13:53.37] ERROR: Parameter name: asyncResult.
```

**Comment by icechat** [comment]
Well, that is a problem with the Async Socket.  Could not establish a connection.
