### ISSUE TITLE
Add 3 icons to left of multiline editbox

### ISSUE THREAD

**Issue by smadAT** [icechat/IceChat#26]
Hello,

 I would like to request that the 3 icons (emoticon picker, color picker, and Help) be re-added to the left when the option View>Multiline Editbox is selected.

![image](https://user-images.githubusercontent.com/40740610/83203592-a050ab00-a0fe-11ea-86a2-1c0af7761f73.png)

Thank you

**Comment by icechat** [comment]
This is implemented in build 9.49.03
