### ISSUE TITLE
Add support for IRCV3 STS

### ISSUE THREAD

**Issue by westor7** [icechat/IceChat#28]
https://ircv3.net/specs/extensions/sts

**Comment by icechat** [comment]
Please provide a server that has this option.

**Comment by westor7** [comment]
irc.chathub.org

6667 = plain
6697 = ssl

if you use 6667 it will force you disconnect and reconnect on 6697 using SSL

(only if server using valid certs)

**Comment by icechat** [comment]
This will be added to 9.51
