### ISSUE TITLE
Refactor ParseData method on ParseIRCData class.

### ISSUE THREAD

**Issue by drielnox** [icechat/IceChat#6]
Code metrics have shown that the rate of maintainability and cyclomatic complexity of [this monstrous method](https://github.com/icechat/IceChat/blob/master/IRCConnection/ParseIRCData.cs#L137-L1765) should be refactored to make it easy to extend and corrected in future.

For that, I will open a [thread on Code Review](http://codereview.stackexchange.com/questions/121885/how-to-refactor-this-monstrous-irc-data-parser) to see who can give suggestions about it.

**Comment by icechat** [comment]
Looks like you are just getting shot down on that website.

**Comment by icechat** [comment]
Since the post was removed from stackexchange, might as well close this.
