### ISSUE TITLE
(user) disconnected from (server) immediately after trying to connect with IPv6

### ISSUE THREAD

**Issue by gbakeman** [icechat/IceChat#9]
When _Connect with IPv6_ is enabled on a favorite server and a connection attempt is made, a blank log is opened with the text (user) disconnected from (server) displayed on the status bar at the bottom. No indication as to why I was immediately disconnected when I attempted to connect. The server supposedly supports IPv6, I have IPv6 enabled in my network stack, and my ISP supports it as well.

errors.log is empty, while the log specific to this server only has the following line:
`Session Start: Sun Mar 20 03:17:13 2016`

**Comment by icechat** [comment]
Error message not being displayed, that the IPv6 address could not be resolved/parsed. Will show for next update.
There is an update to how the IPV6 addresses parse as well, so this should fix the problem with it not parsing.
